// Savollar omborini to'ldirish uchun fanlar va mavzular daraxti (QORALAMA — o'qituvchi tasdiqlashi kerak).
// grades: [boshlanish, tugash] sinf; null = barcha yoshlar uchun. Fan nomlari subjects.ts dagi bilan bir xil bo'lishi shart.

export interface TaxonomyTopic {
    subject: string;
    topic: string;
    grades: [number, number] | null;
}

type Entry = [topic: string, from: number, to: number];

const TREE: Record<string, Entry[]> = {
    'Matematika': [
        ['Natural sonlar va ular ustida amallar', 5, 5],
        ['Oddiy kasrlar', 5, 6],
        ["O'nli kasrlar", 5, 6],
        ['Foizlar va proporsiya', 6, 6],
        ['Butun va ratsional sonlar', 6, 7],
        ["Algebraik ifodalar va ko'phadlar", 7, 7],
        ['Chiziqli tenglamalar va tengsizliklar', 7, 8],
        ['Kvadrat tenglamalar', 8, 8],
        ['Funksiyalar va ularning grafiklari', 8, 9],
        ['Arifmetik va geometrik progressiyalar', 9, 9],
        ['Trigonometriya asoslari', 9, 10],
        ["Ko'rsatkichli va logarifmik funksiyalar", 10, 11],
        ['Hosila va uning tatbiqlari', 10, 11],
        ["Uchburchak va to'rtburchaklar", 7, 8],
        ['Aylana va doira', 8, 8],
        ["Ko'pyoqlar va aylanish jismlari", 10, 11],
        ['Ehtimollar nazariyasi va statistika', 9, 11],
    ],
    'Fizika': [
        ['Moddaning tuzilishi', 6, 7],
        ['Mexanik harakat va tezlik', 7, 7],
        ['Kuch va Nyuton qonunlari', 7, 9],
        ['Suyuqlik va gazlarda bosim', 7, 7],
        ['Ish, quvvat va energiya', 7, 9],
        ['Issiqlik hodisalari', 8, 8],
        ["Elektr toki va Om qonuni", 8, 8],
        ['Magnit maydon', 8, 9],
        ["Mexanik tebranishlar va to'lqinlar", 9, 9],
        ["Yorug'likning qaytishi va sinishi", 9, 9],
        ['Molekulyar fizika va gaz qonunlari', 10, 10],
        ['Elektrostatika', 10, 10],
        ['Elektromagnit induksiya', 11, 11],
        ['Atom va yadro fizikasi', 11, 11],
    ],
    'Kimyo': [
        ['Kimyoning asosiy tushunchalari', 7, 7],
        ['Atom tuzilishi', 7, 8],
        ['Davriy qonun va davriy sistema', 8, 8],
        ["Kimyoviy bog'lanish", 8, 8],
        ['Oksidlar, asoslar, kislotalar va tuzlar', 7, 8],
        ['Kimyoviy reaksiyalar turlari', 8, 8],
        ['Mol, massa va hajm bo\'yicha hisoblashlar', 8, 9],
        ['Eritmalar va elektrolitik dissotsiatsiya', 9, 9],
        ['Metallar', 9, 9],
        ['Metallmaslar', 9, 9],
        ['Uglevodorodlar', 10, 10],
        ['Kislorodli organik birikmalar', 10, 10],
        ["Oqsillar, yog'lar va uglevodlar", 11, 11],
    ],
    'Biologiya': [
        ["O'simlik organlari va tuzilishi", 6, 6],
        ["Fotosintez va o'simliklar hayoti", 6, 6],
        ["Zamburug'lar va bakteriyalar", 6, 6],
        ['Umurtqasiz hayvonlar', 7, 7],
        ['Umurtqali hayvonlar', 7, 7],
        ['Odam skeleti va muskullari', 8, 8],
        ['Qon aylanish va nafas olish tizimi', 8, 8],
        ['Hazm qilish va moddalar almashinuvi', 8, 8],
        ["Asab tizimi va sezgi a'zolari", 8, 8],
        ['Hujayra tuzilishi va funksiyalari', 9, 9],
        ['Genetika asoslari', 9, 10],
        ['Evolyutsion ta\'limot', 10, 11],
        ['Ekologiya va biosfera', 10, 11],
    ],
    'Tarix': [
        ['Qadimgi dunyo sivilizatsiyalari', 5, 6],
        ["Qadimgi O'zbekiston: Baqtriya, So'g'd va Xorazm", 6, 6],
        ['Arab xalifaligi va Movarounnahr', 7, 7],
        ['Somoniylar va Qoraxoniylar davlati', 7, 7],
        ["Mo'g'ullar istilosi", 7, 8],
        ['Amir Temur va Temuriylar davlati', 8, 8],
        ["Buyuk allomalar: Xorazmiy, Beruniy, Ibn Sino, Ulug'bek", 7, 9],
        ['Shayboniylar va xonliklar davri', 8, 9],
        ['Buyuk geografik kashfiyotlar', 8, 8],
        ['Chor Rossiyasi bosqini va mustamlaka davri', 9, 9],
        ['Jadidchilik harakati', 9, 10],
        ["Ikkinchi jahon urushi", 10, 10],
        ["Mustaqil O'zbekiston", 11, 11],
    ],
    'Geografiya': [
        ['Yer va koinot', 5, 5],
        ['Xarita va geografik koordinatalar', 5, 6],
        ['Litosfera va relyef', 6, 6],
        ["Gidrosfera: okeanlar, daryolar va ko'llar", 6, 6],
        ['Atmosfera, ob-havo va iqlim', 6, 6],
        ['Afrika va Yevrosiyo materiklari', 7, 7],
        ['Amerika, Avstraliya va Antarktida', 7, 7],
        ["O'zbekistonning tabiiy geografiyasi", 8, 8],
        ["O'zbekiston viloyatlari va iqtisodiyoti", 9, 9],
        ['Jahon aholisi va davlatlari', 10, 10],
        ["Jahon xo'jaligi", 10, 11],
        ['Tabiatni muhofaza qilish', 9, 11],
    ],
    'Ona tili va adabiyot': [
        ['Fonetika va imlo qoidalari', 5, 5],
        ['Sinonim, antonim va omonimlar', 5, 6],
        ["So'z yasalishi va so'z tarkibi", 6, 6],
        ["Ot, sifat, son va olmosh", 6, 6],
        ["Fe'l va ravish", 6, 7],
        ["Gap bo'laklari", 7, 8],
        ["Qo'shma gaplar", 8, 9],
        ['Tinish belgilari', 7, 9],
        ["Xalq og'zaki ijodi", 5, 6],
        ['Alisher Navoiy ijodi', 8, 9],
        ['Bobur va mumtoz adabiyot', 9, 9],
        ['Abdulla Qodiriy va jadid adabiyoti', 10, 10],
        ["XX asr o'zbek adabiyoti", 10, 11],
        ['Adabiy janrlar va badiiy tasvir vositalari', 7, 11],
    ],
    'Ingliz tili': [
        ["Kundalik hayotga oid so'zlar", 5, 5],
        ['Present Simple va Present Continuous', 5, 6],
        ['Past Simple', 6, 7],
        ['Kelasi zamon shakllari', 7, 7],
        ['Present Perfect', 8, 8],
        ["Modal fe'llar", 8, 8],
        ['Sifat darajalari', 6, 7],
        ['Predloglar', 6, 8],
        ['Shart gaplar (Conditionals)', 9, 10],
        ['Majhul nisbat (Passive voice)', 9, 10],
        ["O'zlashtirma gap (Reported speech)", 10, 11],
        ["Frazali fe'llar va iboralar", 10, 11],
    ],
    'Informatika': [
        ['Kompyuter qurilmalari', 5, 5],
        ["Axborot va uning o'lchov birliklari", 6, 7],
        ['Fayllar va operatsion tizim', 6, 6],
        ['Sanoq sistemalari', 8, 8],
        ['Internet va kompyuter tarmoqlari', 7, 8],
        ['Kiberxavfsizlik va raqamli odob', 7, 9],
        ['Algoritmlar va blok-sxemalar', 8, 8],
        ['Elektron jadvallar', 9, 9],
        ['Python dasturlash asoslari', 9, 10],
        ["Ma'lumotlar bazasi asoslari", 10, 11],
        ["Sun'iy intellekt asoslari", 10, 11],
    ],
};

const GENERAL: string[] = [
    "O'zbekiston madaniyati va an'analari",
    'Dunyo mamlakatlari va poytaxtlari',
    'Ilmiy kashfiyotlar va ixtirolar',
    'Sport va olimpiya o\'yinlari',
    'Mantiqiy fikrlash savollari',
    'Tabiat va hayvonot olami',
];

export const TAXONOMY: TaxonomyTopic[] = [
    ...Object.entries(TREE).flatMap(([subject, entries]) =>
        entries.map(([topic, from, to]) => ({ subject, topic, grades: [from, to] as [number, number] }))
    ),
    ...GENERAL.map(topic => ({ subject: 'Umumiy bilim', topic, grades: null })),
];
